coverage:
  status:
    patch:
      default:
        enabled: no
        
ignore:
  - "CoProject/Infrastructure/Migrations"
  - "CoProject/Client" # for now
  - "CoProject/Infrastructure.Tests"
  - "CoProject/Server.Tests"
