name: Build & Test CI # TODO: Maybe split into two separate workflows?

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
# BACKEND TASKS
      - name: Install dependencies
        working-directory: ./Back-end
        run: dotnet restore
      - name: Build
        working-directory: ./Back-end
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: ./Back-end
        run: dotnet test --no-restore --verbosity normal
# FRONTEND TASKS
      - name: Install dependencies
        working-directory: ./Front-end
        run: dotnet restore
      - name: Build
        working-directory: ./Front-end
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: ./Front-end
        run: dotnet test --no-restore --verbosity normal
